version: ‘3’
services:
  pg:
    image: postgres:15.2-alpine
    container_name: pg
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-password}
      - REPLICATION_PASSWORD=${POSTGRES_PASSWORD-password}
    command: |
      postgres -c config_file=/etc/postgres.conf -c hba_file=/etc/pg_hba.conf
    ports:
      - "5432:5432"
    volumes:
      - ./pg/postgres.conf:/etc/postgres.conf
      - ./pg/pg_hba.conf:/etc/pg_hba.conf
      - ./pg/primary_init_script.sh:/docker-entrypoint-initdb.d/primary_init_script.sh
      - ./pg/primary_create_replica_role.sh:/docker-entrypoint-initdb.d/primary_create_replica_role.sh
      - db:/var/lib/postgresql/data
  pgpool:
    container_name: pgpool
    image: pgpool/pgpool:4.4.2
    links:
      - pg
      - pg-replica
    ports:
      - "9999:9999"
    volumes:
      - ./pgpool/pgpool.conf:/config/pgpool.conf
  pg-replica-init:
    container_name: pg-replica-init
    image: postgres:15.2-alpine
    command: |
      sh -c '/tmp/copy_primary_data_to_replica.sh'
    volumes:
      - ./pg-replica/copy_primary_data_to_replica.sh:/tmp/copy_primary_data_to_replica.sh
      - db-replica:/var/lib/postgresql/data
    environment:
      - PRIMARY_HOST_NAME=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-password}
      - REPLICATION_PASSWORD=${POSTGRES_PASSWORD-password}
  pg-replica:
    container_name: pg-replica
    image: postgres:15.2-alpine
    volumes:
      - ./pg-replica/postgres.conf:/etc/postgres.conf
      - ./pg-replica/pg_hba.conf:/etc/pg_hba.conf
      - db-replica:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - PRIMARY_HOST_NAME=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-password}
      - REPLICATION_PASSWORD=${POSTGRES_PASSWORD-password}
    command: |
      postgres -c config_file=/etc/postgres.conf -c hba_file=/etc/pg_hba.conf
    depends_on:
      pg-replica-init:
        condition: service_started # service_started/service_healthy/service_completed_sucessfully

volumes:
  db:
    driver: local
  db-replica:
    driver: local
